// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACm89x4LMe_4hSCI5uWBQAI-Abv1lX3qk',
    appId: '1:798793215266:web:5b4d85fea796182904497b',
    messagingSenderId: '798793215266',
    projectId: 'crossplateformeflutter',
    authDomain: 'crossplateformeflutter.firebaseapp.com',
    storageBucket: 'crossplateformeflutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXG3I0k-eMchs1WiUlrWNOhUJ6HUw_5IA',
    appId: '1:798793215266:android:d9faf1eeaf4a785904497b',
    messagingSenderId: '798793215266',
    projectId: 'crossplateformeflutter',
    storageBucket: 'crossplateformeflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6hFj_CzslR0Ahflb9yvz1Zl9Kk0BOqig',
    appId: '1:798793215266:ios:10ae4fff61ef2cac04497b',
    messagingSenderId: '798793215266',
    projectId: 'crossplateformeflutter',
    storageBucket: 'crossplateformeflutter.appspot.com',
    iosBundleId: 'com.example.testflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6hFj_CzslR0Ahflb9yvz1Zl9Kk0BOqig',
    appId: '1:798793215266:ios:88b959bcc30f85c504497b',
    messagingSenderId: '798793215266',
    projectId: 'crossplateformeflutter',
    storageBucket: 'crossplateformeflutter.appspot.com',
    iosBundleId: 'com.example.testflutter.RunnerTests',
  );
}
