// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJmsNkmo32HsJzae9mTLFy1p12kPP349o',
    appId: '1:513581437524:web:bac86e24d1132e383053c1',
    messagingSenderId: '513581437524',
    projectId: 'remoteassistant-450a0',
    authDomain: 'remoteassistant-450a0-94c0f.firebaseapp.com',
    storageBucket: 'remoteassistant-450a0.appspot.com',
    measurementId: 'G-L5J1ED3BD0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb2GZnSHbR1Jt3PUT3Flze3ceKjjTV8Kw',
    appId: '1:513581437524:android:2aabed5e83614e063053c1',
    messagingSenderId: '513581437524',
    projectId: 'remoteassistant-450a0',
    storageBucket: 'remoteassistant-450a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAimfYl02-7mD76-k7GW4ZPjtpYtedfAT4',
    appId: '1:513581437524:ios:67a44af1ca9437783053c1',
    messagingSenderId: '513581437524',
    projectId: 'remoteassistant-450a0',
    storageBucket: 'remoteassistant-450a0.appspot.com',
    iosBundleId: 'com.example.testflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAimfYl02-7mD76-k7GW4ZPjtpYtedfAT4',
    appId: '1:513581437524:ios:42e17344f09a6dca3053c1',
    messagingSenderId: '513581437524',
    projectId: 'remoteassistant-450a0',
    storageBucket: 'remoteassistant-450a0.appspot.com',
    iosBundleId: 'com.example.testflutter.RunnerTests',
  );
}
