// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2U1hQUJX_BcpwKer6NaTkR43tf6lYTGg',
    appId: '1:963567142265:web:8c0f702040eabd0d071ba8',
    messagingSenderId: '963567142265',
    projectId: 'remotea-33fc5',
    authDomain: 'remotea-33fc5.firebaseapp.com',
    storageBucket: 'remotea-33fc5.appspot.com',
    measurementId: 'G-W0LHRSMLNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHEYoQShmt4fTC_j0OX1IH2XOeqQv1Oxk',
    appId: '1:963567142265:android:f6a7e6503a6876ae071ba8',
    messagingSenderId: '963567142265',
    projectId: 'remotea-33fc5',
    storageBucket: 'remotea-33fc5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFLYrJMlDyk5E0P06hrpkjjZgQHvThois',
    appId: '1:963567142265:ios:510a5f21aa691a7b071ba8',
    messagingSenderId: '963567142265',
    projectId: 'remotea-33fc5',
    storageBucket: 'remotea-33fc5.appspot.com',
    iosBundleId: 'com.example.testflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFLYrJMlDyk5E0P06hrpkjjZgQHvThois',
    appId: '1:963567142265:ios:423c4ee29e69b752071ba8',
    messagingSenderId: '963567142265',
    projectId: 'remotea-33fc5',
    storageBucket: 'remotea-33fc5.appspot.com',
    iosBundleId: 'com.example.testflutter.RunnerTests',
  );
}
